# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/item.ui'
#
# Created: Fri Jan 21 12:13:11 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

import gettext
__trans = gettext.translation('service-manager', fallback=True)
i18n = __trans.ugettext
from PyQt4 import QtCore, QtGui

class Ui_ServiceItemWidget(object):
    def setupUi(self, ServiceItemWidget):
        ServiceItemWidget.setObjectName("ServiceItemWidget")
        ServiceItemWidget.resize(632, 48)
        ServiceItemWidget.setMinimumSize(QtCore.QSize(0, 48))
        self.mainLayout = QtGui.QHBoxLayout(ServiceItemWidget)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.spacer = QtGui.QWidget(ServiceItemWidget)
        self.spacer.setMinimumSize(QtCore.QSize(4, 0))
        self.spacer.setMaximumSize(QtCore.QSize(4, 16777215))
        self.spacer.setObjectName("spacer")
        self.mainLayout.addWidget(self.spacer)
        self.labelStatus = QtGui.QLabel(ServiceItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMinimumSize(QtCore.QSize(36, 0))
        self.labelStatus.setText("")
        self.labelStatus.setPixmap(QtGui.QPixmap("icons/stopped.png"))
        self.labelStatus.setObjectName("labelStatus")
        self.mainLayout.addWidget(self.labelStatus)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelName = QtGui.QLabel(ServiceItemWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.labelDesc = QtGui.QLabel(ServiceItemWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelDesc.setFont(font)
        self.labelDesc.setStyleSheet("color:gray;")
        self.labelDesc.setObjectName("labelDesc")
        self.verticalLayout.addWidget(self.labelDesc)
        self.mainLayout.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(308, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.mainLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonStart = QtGui.QPushButton(ServiceItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStart.sizePolicy().hasHeightForWidth())
        self.buttonStart.setSizePolicy(sizePolicy)
        self.buttonStart.setMaximumSize(QtCore.QSize(36, 16777215))
        self.buttonStart.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/data/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStart.setIcon(icon)
        self.buttonStart.setFlat(True)
        self.buttonStart.setObjectName("buttonStart")
        self.gridLayout.addWidget(self.buttonStart, 0, 0, 1, 1)
        self.buttonReload = QtGui.QPushButton(ServiceItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonReload.sizePolicy().hasHeightForWidth())
        self.buttonReload.setSizePolicy(sizePolicy)
        self.buttonReload.setMaximumSize(QtCore.QSize(36, 16777215))
        self.buttonReload.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/data/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonReload.setIcon(icon1)
        self.buttonReload.setFlat(True)
        self.buttonReload.setObjectName("buttonReload")
        self.gridLayout.addWidget(self.buttonReload, 0, 1, 1, 1)
        self.checkStart = QtGui.QCheckBox(ServiceItemWidget)
        self.checkStart.setObjectName("checkStart")
        self.gridLayout.addWidget(self.checkStart, 0, 4, 1, 1)
        self.buttonStop = QtGui.QPushButton(ServiceItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStop.sizePolicy().hasHeightForWidth())
        self.buttonStop.setSizePolicy(sizePolicy)
        self.buttonStop.setMaximumSize(QtCore.QSize(36, 16777215))
        self.buttonStop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/data/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStop.setIcon(icon2)
        self.buttonStop.setFlat(True)
        self.buttonStop.setObjectName("buttonStop")
        self.gridLayout.addWidget(self.buttonStop, 0, 2, 1, 1)
        self.buttonInfo = QtGui.QPushButton(ServiceItemWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInfo.sizePolicy().hasHeightForWidth())
        self.buttonInfo.setSizePolicy(sizePolicy)
        self.buttonInfo.setMaximumSize(QtCore.QSize(36, 16777215))
        self.buttonInfo.setText("")
        self.buttonInfo.setFlat(True)
        self.buttonInfo.setObjectName("buttonInfo")
        self.gridLayout.addWidget(self.buttonInfo, 0, 3, 1, 1)
        self.mainLayout.addLayout(self.gridLayout)

        self.retranslateUi(ServiceItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ServiceItemWidget)

    def retranslateUi(self, ServiceItemWidget):
        ServiceItemWidget.setWindowTitle(i18n("Form"))
        self.labelName.setText(i18n("serviceName"))
        self.labelDesc.setText(i18n("serviceDesc"))
        self.buttonStart.setToolTip(i18n("Start service"))
        self.buttonReload.setToolTip(i18n("Reload service"))
        self.checkStart.setText(i18n("Run on start"))
        self.buttonStop.setToolTip(i18n("Stop service"))
        self.buttonInfo.setToolTip(i18n("More Information"))

