"""
mdiview.py - view component

copyright: (C) 2001, Boudewijn Rempt
email:     boud@rempt.xs4all.nl

This framework is based on the template generated by KDevelop
"""
from qt import *

class MDIView(QWidget):
    """
    The MDIView class can represent object of class
    MDIDoc on screen.

    slots:
          slotDocModified
    """
    def __init__(self, doc, parent, name, flags):
        QWidget.__init__(self, parent, name, flags)
        self.doc = doc
        
        self.connect(self.doc, PYSIGNAL("sigDocModified"),
                     self.slotDocModified)
        self.connect(self.doc, PYSIGNAL("sigDocTitleChanged"),
                     self.setCaption)
        # Set initial values
        self.slotDocModified(self.doc.isModified())
        
    def slotDocModified(self, value):
        if value:
            self.setBackgroundColor(QColor("red"))
        else:
            self.setBackgroundColor(QColor("green")) 

    def mouseDoubleClickEvent(self, ev):
        self.doc.slotModify() # direct call to the document

    def document(self):
        return self.doc

    def closeEvent(self, ev):
        # LEAVE THIS EMPTY: THE EVENT FILTER IN THE MdiApp CLASS TAKES
        # CARE OF CLOSING. QWidget closeEvent must be prevented.
        pass
